"""empty message

Revision ID: 9be6eafd7a40
Revises: 0305c001380c
Create Date: 2021-03-19 21:28:05.803580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be6eafd7a40'
down_revision = '0305c001380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('modified_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
