"""empty message

Revision ID: c30db3204f47
Revises: 9be6eafd7a40
Create Date: 2021-03-20 09:37:20.633552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30db3204f47'
down_revision = '9be6eafd7a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('breed', sa.String(length=128), nullable=False),
    sa.Column('eye_color', sa.String(length=128), nullable=False),
    sa.Column('body_color', sa.String(length=128), nullable=False),
    sa.Column('opt_color', sa.String(length=16), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horses')
    # ### end Alembic commands ###
